### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by PaulSchulz**
Minor typo

### CODE REVIEW

**Comment by smee** [comment]
Thanks!

**Comment by PaulSchulz** [comment]
Quick question..

How do  parse/input a list of ints (:uint-le) where the first contains the
number of ints to read?

Do I need to read the first (:size) and then parse the rest with 'repeat'
with parameter (as code) or is there a way to set this in the data
specification?

Cheers,
Paul

**Comment by smee** [comment]
You could either use `(repeated :uint-le :prefix :uint-le)` for repeated elements with a length prefix, or the more generalized `(header :uint-le (fn [len] (repeated :uint-le :length len)) count)` which can be used for any kind of header/body encoding. For examples please refer to the tests, for example at https://github.com/smee/binary/blob/master/test/org/clojars/smee/binary/codectests.clj#L125 or https://github.com/smee/binary/blob/master/test/org/clojars/smee/binary/codectests.clj#L204

**Comment by PaulSchulz** [comment]
Awesome. Thats exactly what I needed.

**Pull request merged**
